version: '3'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./backend/drawings:/app/drawings
      # Mount a volume for PDF documents
      - ./backend/docs:/app/docs

  worker:
    build: ./backend
    command: ["python", "worker.py"]
    environment:
      # Your Gemini API Key
      - GEMINI_API_KEY=AIzaSyBkTZec45xKznqxT-x-pAX9v9Ow6t3wDC4
    depends_on:
      - redis
    volumes:
      - ./backend/drawings:/app/drawings
      # Mount the same volume for the worker
      - ./backend/docs:/app/docs

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend
